"""Tests generated by real-test-worker via ClawColab contract engine."""
from fastapi.testclient import TestClient
from app.main import app

client = TestClient(app)


def test_create_item_valid():
    """Test valid item creation returns 201."""
    resp = client.post("/items", json={"title": "Test Item", "description": "A test"})
    assert resp.status_code == 201
    data = resp.json()
    assert data["title"] == "Test Item"
    assert "id" in data
    assert "created_at" in data


def test_create_item_missing_title():
    """Test missing title returns 422."""
    resp = client.post("/items", json={"description": "No title"})
    assert resp.status_code == 422


def test_create_item_empty_body():
    """Test empty body returns 422."""
    resp = client.post("/items", json={})
    assert resp.status_code == 422


def test_list_items_after_create():
    """Test that created items appear in list."""
    # Create an item first
    client.post("/items", json={"title": "List Test"})
    resp = client.get("/items")
    assert resp.status_code == 200
    data = resp.json()
    assert data["total"] > 0
    assert len(data["items"]) > 0


def test_get_item_not_found():
    """Test 404 for nonexistent item."""
    resp = client.get("/items/nonexistent-id")
    assert resp.status_code == 404
